'use client';

import { useRouter } from 'next/navigation';
import { ArrowLeft, Flag } from 'lucide-react';

export default function ModerationPage() {
  const router = useRouter();
  return <main className="min-h-screen bg-[#09090b] px-4 py-12 font-sans text-zinc-100"><div className="mx-auto max-w-3xl"><button onClick={() => router.back()} className="mb-8 inline-flex items-center gap-2 text-sm font-medium text-zinc-400 hover:text-white"><ArrowLeft size={16} /> Back</button><article className="rounded-[2.5rem] border border-zinc-800 bg-[#09090b]/80 p-8 shadow-2xl backdrop-blur-2xl md:p-12"><header className="mb-8 flex items-center gap-4 border-b border-zinc-800 pb-8"><div className="flex h-12 w-12 items-center justify-center rounded-xl border border-amber-500/20 bg-amber-600/10"><Flag className="h-6 w-6 text-amber-500" /></div><div><h1 className="text-3xl font-black">Moderation Policy</h1><p className="mt-1 text-zinc-400">Last updated: July 20, 2026</p></div></header><div className="space-y-7 text-sm leading-relaxed text-zinc-300 md:text-base"><section><h2 className="mb-2 text-xl font-bold text-white">Reporting</h2><p>Users can report accounts, messages, stories, and groups in the app. Reports may include the selected category and details supplied by the reporter.</p></section><section><h2 className="mb-2 text-xl font-bold text-white">Review and Outcomes</h2><p>We review reports in a timely, diligent, non-arbitrary, and objective manner. We may take no action, remove content, warn a user, limit features, mute, temporarily suspend, or permanently ban an account. Serious safety or security issues may result in immediate action.</p></section><section><h2 className="mb-2 text-xl font-bold text-white">Reasons and Appeals</h2><p>Where appropriate, we will tell an affected user what action was taken and why. As a personal project without a dedicated support channel today, appeals cannot currently be requested by email; this policy will be updated if a contact channel is added.</p></section><section><h2 className="mb-2 text-xl font-bold text-white">Evidence and False Reports</h2><p>We may keep limited report and moderation records for safety, fraud prevention, and legal claims, then delete or anonymize them when no longer needed. Knowingly false or abusive reports may lead to restrictions.</p></section></div></article></div></main>;
}
